parameters:
    images_directory: '%kernel.project_dir%/public/assets/img'
    logos_directory: '%kernel.project_dir%/public/assets/img'    
twig:
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
